codecov:
  branch: main
  token: ${{ secrets.CODECOV_TOKEN }}
  strict_yaml_branch: default

coverage:
  status:
    project:
      default:
        threshold: 0%
        target: 100%
        base: auto
        flags:
          - unittests
        paths:
          - "helmeos"
          - "tests"

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
